#version: '3.8'  # ✅ Version must be on top
services:
   # API Gateway
  api-gateway:
    container_name: apigateway
    build:
      context: .
      dockerfile: Services/ApiGateway/Dockerfile
    ports:
      - "5500:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- AuthApiUrl=http://auth-api:6100
    networks:
      - microMart
     # Auth Service
  auth-api:
    container_name: auth-api
    build:
      context: .
      dockerfile: Services/Auth.API/Dockerfile
    ports:
      - "6100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - microMart 

  user-api:
    container_name: user-api
    build:
      context: .
      dockerfile: Services/User.API/Dockerfile
    ports:
      - "6600:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - microMart   

  notification-api:
    container_name: notification-api
    build:
      context: .
      dockerfile: Services/Notification.API/Dockerfile
    ports:
      - "5101:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - microMart  

  cart-api:
    container_name: Cart-api
    build:
      context: .
      dockerfile: Services/Cart.API/Dockerfile
    ports:
      - "6200:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - microMart 

  inventory-api:
    container_name: inventory-api
    build:
      context: .
      dockerfile: Services/Inventory.API/Dockerfile
    ports:
      - "6300:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - microMart 
  
  order-api:
    container_name: order-api
    build:
      context: .
      dockerfile: Services/Order.API/Dockerfile
    ports:
      - "6400:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - microMart 

  product-api:
    container_name: product-api
    build:
      context: .
      dockerfile: Services/Product.API/Dockerfile
    ports:
      - "6500:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
        - microMart 

networks:
  microMart:
    external: true  # Declare existing network here # Must declare this  network as external if it exists

  # Cart Service

